import { ElementProps, ElementItemStatusProps } from './element';
import { elementItemStatus } from './elementItemStatus';
import { InstallationProps } from './installations';
import { ParentType } from './parent';
import { IunitOfMeasure, UnitProps } from './unit';

export type StorageProps = {
  name: any;
  supplier: any;
  dateLastPurchase: string | number | Date;
  quantityMinimal: any;
  quantityMaximum: any;
  quantityStock: any;
  id: string;
  installation: InstallationProps;
  location: string;
  element: ElementProps;
  parent: ParentType;
  lot: string;
  containerNumber: string;
  prioLabId: string;
  volume: number;
  unitOfMeasure: IunitOfMeasure;
  unit: string;
  elementItemStatusId: string;
  elementItemStatus: elementItemStatus;
  observations: string;
  manufactureDate: Date;
  expiryDate: Date;
  arrivalDate: Date;
  decantingDate: Date;
  unloadingDate: Date;
  slingId: string;
  slingCertificate: string;
  slingValidity: Date;
  isActive: boolean;
  isUsed: boolean;
  volumeUnit: string;
  isDecanting: boolean;
  parentId: string;
  elementId: string;
};

export type StoragePropsEdit = Partial<StorageProps>;
